# Configuration file for Playwright Navigation Demo
# This file contains all configurable parameters for web scraping operations

scraping:
  # Browser configuration
  browser_type: "chromium"  # Options: chromium, firefox, webkit
  headless: true           # Set to false for debugging with visible browser
  
  # Timing and retry settings
  timeout: 30000          # Default timeout in milliseconds
  max_retries: 3          # Maximum number of retry attempts
  delay_between_requests: 1.0  # Delay between requests in seconds
  
  # Viewport settings
  viewport_width: 1280    # Browser viewport width
  viewport_height: 720    # Browser viewport height
  
  # Optional user agent (leave empty for default)
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# Demo-specific settings
demo:
  # Sites to use for testing (can be modified for different targets)
  test_sites:
    dynamic_content: "https://github.com/trending"
    navigation: "https://en.wikipedia.org/wiki/Wikipedia:Featured_articles"
    structured_data: "https://news.ycombinator.com/"
  
  # Output settings
  save_screenshots: false  # Save screenshots during demos
  verbose_logging: true    # Enable detailed logging
  
  # Error simulation settings
  simulate_errors: true    # Include error handling demonstrations

# Logging configuration
logging:
  level: "INFO"           # Options: DEBUG, INFO, WARNING, ERROR
  file: "playwright_demo.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"